name: RPS CD

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - uses: DamianReeves/write-file-action@master
        with:
          path: ./src/environments/environment.prod.ts
          contents: |
            ${{ secrets.FIREBASE_CONFIG }}
          write-mode: overwrite
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build-prod
      - uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      - name: Install function dependencies
        working-directory: ./firebase-functions/functions
        run: npm ci
      - name: Build functions
        working-directory: ./firebase-functions/functions
        run: npm run build
      - name: Deploy functions
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_PATH: firebase-functions/